# Generated by Django 3.1.2 on 2021-04-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(choices=[('Pint', 'Pint'), ('Schooner', 'Schooner'), ('Half-Pint', 'Half-Pint'), ('1/3 Pint', '1/3 Pint')], max_length=10, null=True)),
                ('price', models.FloatField(null=True)),
                ('beer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.beer')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.venue')),
            ],
        ),
    ]
