# Generated by Django 3.1.2 on 2021-04-30 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
