# Generated by Django 3.1.2 on 2021-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='submitted_by',
            field=models.CharField(default='Anonymous User', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
