# Generated by Django 3.1.2 on 2021-05-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210520_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='google_maps_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
