# Generated by Django 3.1.2 on 2021-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bugreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreports',
            name='submitted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='submitted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
