# Generated by Django 3.1.2 on 2021-05-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210521_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreports',
            options={'verbose_name_plural': 'Bug Reports'},
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
