# Generated by Django 3.1.2 on 2021-05-22 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210522_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='overall_rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
