# Generated by Django 3.1.2 on 2021-05-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rating_overall_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
