# Generated by Django 3.1.2 on 2021-05-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value_for_money_rating',
            new_name='venue_rating',
        ),
    ]
