# Generated by Django 3.1.2 on 2021-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210523_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20000, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('submitted_on', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
            },
        ),
    ]
